name: examples-win-x64 

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: windows-2022
    steps:
    
      - name: Check out repository
        uses: actions/checkout@v3 

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build SIP Examples
        run: |
          dotnet build examples/sipexamples/sipexamples.sln
          
      - name: Build WebRTC Examples
        run: |
          dotnet build examples/webrtcexamples/webrtcexamples.sln
          
      - name: Build WebRTC Command Line Example
        run: |
          dotnet build examples/webrtccmdline/webrtccmdline.sln
          
      - name: Build SIP Command Line Example
        run: | 
          dotnet build examples/sipcmdline/sipcmdline.sln --configuration Release
          
      - name: Build STUN Server Example
        run: |     
          dotnet build examples/stunserver/stunserver.sln
          
      - name: Build Soft Phone Example
        run: |        
          dotnet build examples/softphone/sipsorcery.softphone.sln --configuration Release
